name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres@sha256:ca34600b1f2f21c033b4761d88cf763a64201c3af16cffe22d26375c2b9956e3
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run PostgreSQL migrations
      env:
        PGPASSWORD: postgres
      run: |
        for file in docker/postgres/*
        do
          if [[ "$file" =~ V0 ]]; then
            psql -h localhost -U postgres postgres -f "$file"
          else
            psql -h localhost -U postgres techmaps -f "$file"
          fi
        done
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
