name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres@sha256:8d3be35b184e70d81e54cbcbd3df3c0b47f37d06482c0dd1c140db5dbcc6a808
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Set up JDK 17
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run PostgreSQL migrations
      env:
        PGPASSWORD: postgres
      run: |
        for file in docker/postgres/*
        do
          if [[ "$file" =~ V0 ]]; then
            psql -h localhost -U postgres postgres -f "$file"
          else
            psql -h localhost -U postgres techmaps -f "$file"
          fi
        done
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
