name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres@sha256:994cc3113ce004ae73df11f0dbc5088cbe6bb0da1691dd7e6f55474202a4f211
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up JDK 17
      uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run PostgreSQL migrations
      env:
        PGPASSWORD: postgres
      run: |
        for file in docker/postgres/*
        do
          if [[ "$file" =~ V0 ]]; then
            psql -h localhost -U postgres postgres -f "$file"
          else
            psql -h localhost -U postgres techmaps -f "$file"
          fi
        done
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
